from ._exceptions import ResultTypeError